version: '3.9'

services:
  web:
    build:
      context: .
    container_name: vpn-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - vpn-network

  celery:
    build:
      context: .
    container_name: vpn-celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - vpn-network

  redis:
    image: redis:7
    container_name: vpn-redis
    ports:
      - "6379:6379"
    networks:
      - vpn-network

networks:
  vpn-network:
