# Generated by Django 5.2 on 2025-05-01 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('type', models.CharField(choices=[('balance', 'Пополнение баланса'), ('subscription', 'Подарочная подписка')], max_length=20, verbose_name='Тип промокода')),
                ('expiration_date', models.DateTimeField(verbose_name='Действует до')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма пополнения')),
                ('vpn_type', models.CharField(blank=True, choices=[('solo', 'Одиночный VPN'), ('double', 'Двойной VPN'), ('triple', 'Тройной VPN')], max_length=10, null=True, verbose_name='Тип VPN')),
                ('duration', models.CharField(blank=True, choices=[('1m', '1 месяц'), ('6m', '6 месяцев'), ('1y', '1 год'), ('3y', '3 года')], max_length=2, null=True, verbose_name='Срок')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Использовавший')),
            ],
        ),
    ]
