# Generated by Django 5.2 on 2025-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='vpn_type',
            field=models.CharField(blank=True, choices=[('solo', 'Одиночный VPN'), ('double', 'Двойной VPN')], max_length=10, null=True, verbose_name='Тип VPN'),
        ),
    ]
