# Generated by Django 5.2 on 2025-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='vpn_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='vpn_usage',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('torrents', 'Торренты'), ('social', 'Соцсети'), ('gaming', 'Игры'), ('streaming', 'Стриминг')], max_length=20, null=True, verbose_name='Назначение VPN'),
        ),
    ]
