# Generated by Django 5.2 on 2025-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_remove_coupon_vpn_type_coupon_vpn_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='vpn_usage',
        ),
        migrations.AddField(
            model_name='coupon',
            name='vpn_type',
            field=models.CharField(blank=True, choices=[('solo', 'Одиночный VPN'), ('double', 'Двойной VPN')], max_length=10, null=True, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.CharField(blank=True, choices=[('1m', '1 месяц'), ('6m', '6 месяцев'), ('1y', '1 год'), ('3y', '3 года')], max_length=2, null=True, verbose_name='Срок'),
        ),
    ]
