# Generated by Django 5.2.1 on 2025-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_remove_coupon_vpn_usage_coupon_vpn_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='vpn_type',
            field=models.CharField(blank=True, choices=[('socials', 'Для YouTube и соцсетей'), ('torrents', 'Для торрентов'), ('secure', '🛡 Двойное шифрование'), ('country', '🌐 Выбор по стране')], max_length=10, null=True, verbose_name='Тип VPN'),
        ),
    ]
