# Generated by Django 5.2.3 on 2025-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_alter_coupon_vpn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.CharField(blank=True, choices=[('5d', '5 дней'), ('1m', '1 месяц'), ('3m', '3 месяца'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='vpn_type',
            field=models.CharField(blank=True, choices=[('socials', 'Для соцсетей'), ('torrents', 'Для загрузки файлов'), ('secure', '🛡 Двойное шифрование'), ('country', '🌐 Выбор по стране'), ('serfing', 'Для серфинга')], max_length=10, null=True, verbose_name='Тип VPN'),
        ),
    ]
