# Generated by Django 5.2.3 on 2025-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_alter_coupon_duration_alter_coupon_vpn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.CharField(blank=True, choices=[('1m', '1 месяц'), ('3m', '3 месяца'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, null=True, verbose_name='Срок'),
        ),
    ]
