# Generated by Django 5.2 on 2025-05-04 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('raw_log', models.TextField(verbose_name='Исходный лог')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домен')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Статус')),
                ('bytes_sent', models.IntegerField(blank=True, null=True, verbose_name='Отправлено байт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
