# Generated by Django 5.2.1 on 2025-05-18 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_logs', '0002_remove_proxylog_user_alter_proxylog_remote_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
