# Generated by Django 5.2.1 on 2025-05-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_logs', '0003_proxylog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxylog',
            options={'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
    ]
