# Generated by Django 5.2 on 2025-04-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMESS'), ('wireguard', 'WireGuard')], max_length=20)),
                ('limit_per_user', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_type', models.CharField(choices=[('mobile', 'Мобильный'), ('residential', 'Резидентский'), ('rotating', 'С ротацией')], max_length=20)),
                ('duration', models.CharField(choices=[('1m', '1 месяц'), ('6m', '6 месяцев'), ('12m', '1 год'), ('36m', '3 года')], max_length=4)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'unique_together': {('vpn_type', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='VPNKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vpn_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vpnuser')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_api.vpnserver')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('vpn_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vpnuser')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_api.tariff')),
                ('vpn_key', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_api.vpnkey')),
            ],
        ),
    ]
