# Generated by Django 5.2 on 2025-04-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0002_subscriptionplan_remove_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_paused_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
