# Generated by Django 5.2 on 2025-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0004_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deactivation_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи деактивации'),
        ),
    ]
