# Generated by Django 5.2 on 2025-04-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0005_subscription_deactivation_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='deactivation_task_id',
        ),
    ]
