# Generated by Django 5.2 on 2025-04-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0007_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
