# Generated by Django 5.2 on 2025-05-03 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0009_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='vless',
            field=models.TextField(blank=True, null=True, verbose_name='VLESS конфиг'),
        ),
    ]
