# Generated by Django 5.2 on 2025-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0010_subscription_vless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='vless',
            field=models.TextField(blank=True, null=True, verbose_name='VLESS конфиг'),
        ),
    ]
