# Generated by Django 5.2 on 2025-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0011_alter_subscription_vless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='vpn_type',
            field=models.CharField(choices=[('solo', 'Одиночный VPN'), ('double', 'Двойной VPN')], max_length=10, verbose_name='Тип впн'),
        ),
    ]
