# Generated by Django 5.2 on 2025-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0012_alter_subscriptionplan_vpn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('youtube', 'Для YouTube и соцсетей'), ('torrents', 'Для торрентов'), ('secure', 'Двойное шифрование'), ('country', 'Выбор по стране')], default='youtube', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='vpn_type',
            field=models.CharField(choices=[('solo', 'Одиночный VPN'), ('double', 'Двойной VPN')], max_length=10, verbose_name='Тип VPN'),
        ),
    ]
