# Generated by Django 5.2 on 2025-05-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0013_subscriptionplan_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='vpn_type',
        ),
    ]
