# Generated by Django 5.2 on 2025-05-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0014_remove_subscriptionplan_vpn_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='category',
            new_name='vpn_type',
        ),
    ]
