# Generated by Django 5.2 on 2025-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0015_rename_category_subscriptionplan_vpn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='vpn_type',
            field=models.CharField(
                choices=[
                    ('socials', 'для соц.сетей'),
                    ('torrents', 'Для загрузки файлов'),
                    ('secure', '🛡 Двойное шифрование'),
                    ('country', '🌐 Выбор по стране'),
                    ('serfing', 'Для серфинга'),
                ],
                max_length=10,
                verbose_name='Тип впн'
            ),
        ),
    ]
