# Generated by Django 5.2.1 on 2025-05-20 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0016_alter_subscriptionplan_vpn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
    ]
