# Generated by Django 5.2.1 on 2025-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0017_subscription_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_active',
            field=models.BooleanField(default=False, verbose_name='Скидка активна'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст скидки (для отображения в боте)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('1m', '1 месяц'), ('3m', '3 месяцев'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, verbose_name='Длительность'),
        ),
    ]
