# Generated by Django 5.2.1 on 2025-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0018_subscriptionplan_discount_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка в %'),
        ),
    ]
