# Generated by Django 5.2.2 on 2025-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0020_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('name', models.CharField(max_length=100, verbose_name='Название (например, us1)')),
                ('domain', models.CharField(max_length=255, verbose_name='Домен (например, us1.anonixvpn.space)')),
                ('api_url', models.URLField(verbose_name='FastAPI URL (https://domain/api)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
    ]
