# Generated by Django 5.2.3 on 2025-06-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0021_vpnserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='vpnserver',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn_api.vpnserver', verbose_name='VPN сервер'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpn_api.subscriptionplan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('5d', '5 дней'), ('1m', '1 месяц'), ('3m', '3 месяца'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, verbose_name='Длительность'),
        ),
    ]
