# Generated by Django 5.2.3 on 2025-06-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0022_alter_subscription_options_alter_vpnserver_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paused',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount_text',
        ),
    ]
