# Generated by Django 5.2.3 on 2025-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_api', '0023_remove_subscription_paused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('1m', '1 месяц'), ('3m', '3 месяца'), ('6m', '6 месяцев'), ('1y', '1 год')], max_length=2, verbose_name='Длительность'),
        ),
    ]
