# Generated by Django 5.2 on 2025-04-23 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referred_by', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
