# Generated by Django 5.1.6 on 2025-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('vpn_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vpn_type', models.CharField(choices=[('single', 'Одиночный VPN'), ('double', 'Двойной VPN'), ('triple', 'Тройной VPN')], default='single', max_length=20)),
            ],
        ),
    ]
