# Generated by Django 5.2 on 2025-04-22 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='vpn_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
