# Generated by Django 5.2 on 2025-05-03 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vpnuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
