# Generated by Django 5.2.3 on 2025-06-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_vpnuser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnuser',
            name='current_ip',
        ),
        migrations.RemoveField(
            model_name='vpnuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vpnuser',
            name='is_banned',
        ),
    ]
