# Generated by Django 5.2.3 on 2025-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_vpnuser_current_ip_remove_vpnuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина бана'),
        ),
        migrations.AddField(
            model_name='vpnuser',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата бана'),
        ),
        migrations.AddField(
            model_name='vpnuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
    ]
