# Generated by Django 5.2.3 on 2025-06-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_vpnuser_promo_code_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='referral_discount_used',
            field=models.BooleanField(default=False, verbose_name='Реферальная скидка использована'),
        ),
    ]
